version: "3.8"

services:
  client:
    build:
      context: ./Client
    networks:
      - frontend
    ports:
      - "3000:3000"
    volumes:
      - ./Client:/app

  # ===========================================================================================================================

networks:
  frontend:
